---
- name: set dns entries for EL based linux distros
  hosts: linux
  become: true
  tasks:
  - name: set dns for EL 7 based servers
    nmcli:
      conn_name: "{{ ansible_default_ipv4.interface }}"
      type: ethernet
      dns4: "{{ item }}"
      state: present
    with_items: "{{ dns_servers }}"
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_major_ver =='7'
    notify:
      - reload network interfaces
      - restart NetworkManager
      - wait for new network settings
      
  - name: Set DNS entries for EL 6 based servers


  handlers:
  - name: reload network interface
    shell: nmcli con reload 
  - name: restart NetworkManager 
    service: name=NetworkManager state=restarted 
  - name: wait for new network settings
    sudo: false 
    local_action: 
      module: wait_for host={{ ansible_ssh_host | default(inventory_hostname) }} port=22 delay=10 timeout=300
