---
- name: Testing out some user limitations
  hosts: all
  gather_facts: yes

  tasks:
    - name: What user is running this
      shell: whoami
      register: whoami_result

    - name: display the result of the whoami
      debug:
        var: whoami_result

  block:
    become: yes
    - name: A command for only root users
      shell: cat /etc/shadow
      register: rootcmd_result

    - name: display the result of the root user command
      debug:
        var: rootcmd_result

