---
- name: EL7-ONLY Configure resolv.conf on EL7
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
  register: resolvFile
  tags: makeitso

- name: activate_config
  nmcli:
    conn_name: "{{ ansible_default_ipv4.interface }}"
    type: ethernet
    dns4: "{{ resolv_nameservers }}"
    state: present
  when: resolvFile.changed

- name: activate_network
  command: /usr/bin/nmcli connection up "{{ ansible_default_ipv4.interface }}"
  when: resolvFile.changed


## Debugging stuff below here


- name: EL7-ONLY debugging to check interface status
  command: /usr/bin/nmcli dev show "{{ ansible_default_ipv4.interface }}"
  register: devshow_output
  changed_when: False
  tags: debug

- name: EL7-ONLY debug output of the file
  debug:
    msg: "{{ devshow_output.stdout_lines }}"
  tags: debug

- name: EL7-ONLY debugging to check /etc/resolv.conf
  command: "cat /etc/resolv.conf"
  register: etcresolv_output
  changed_when: False
  tags: debug

- name: EL7-ONLY debug output of the file
  debug:
    msg: "{{ etcresolv_output.stdout_lines }}"
  changed_when: False
  tags: debug

- name: LINUX-ONLY debugging to resolve a domain if possible
  command: nslookup "{{ lookup_test }}"
  register: lookup_output
  changed_when: False
  tags: debug

- name: LINUX-ONLY debug output of the resolution
  debug:
    msg: "{{ lookup_output }}"
  tags: debug

