---
- name: Check running config via resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
  register: resolvFile
  tags: makeitso

- name: Apply new network config if necessary
  nmcli:
    conn_name: "{{ ansible_default_ipv4.interface }}"
    type: ethernet
    dns4: "{{ resolv_nameservers }}"
    state: present
  when: resolvFile.changed

- name: Activate new network config if necessary
  command: /usr/bin/nmcli connection up "{{ ansible_default_ipv4.interface }}"
  when: resolvFile.changed


## Debugging stuff below here


- name: Check interface current status
  command: /usr/bin/nmcli dev show "{{ ansible_default_ipv4.interface }}"
  register: devshow_output
  changed_when: False
  tags: debug

- name: Debug output of interface current status
  debug:
    msg: "{{ devshow_output.stdout_lines }}"
  tags: debug

- name: Check /etc/resolv.conf
  command: "cat /etc/resolv.conf"
  register: etcresolv_output
  changed_when: False
  tags: debug

- name: Debug output of /etc/resolv.conf
  debug:
    msg: "{{ etcresolv_output.stdout_lines }}"
  changed_when: False
  tags: debug

- name: Check if we can resolve DNS for "{{ lookup_test }}"
  command: nslookup "{{ lookup_test }}"
  register: lookup_output
  changed_when: False
  tags: debug

- name: Debug output of DNS lookup for "{{ lookup_test }}"
  debug:
    msg: "{{ lookup_output }}"
  tags: debug

