---
- name: resolv.conf validation
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
  tags: makeitso

- name: change nameserver settings in the interfaces file
  interfaces_file:
    dest: /etc/network/interfaces
    iface: "{{ ansible_default_ipv4.interface }}"
    option: dns-nameservers
    value: "{{ resolv_nameservers[0]|default ('') }} {{ resolv_nameservers[1]|default ('') }} {{ resolv_nameservers[2]|default ('') }}"	
    backup: yes
    state: present
  tags: makeitso

- name: debugging to check /etc/resolv.conf
  command: cat /etc/network/interfaces
  register: interface_output
  changed_when: False
  tags: debug

- name: debug output of the file
  debug:
    msg: "{{ interface_output.stdout_lines }}"
  tags: debug

- name: debugging to resolve a domain if possible
  command: nslookup "{{ lookup_test }}"
  register: lookup_output
  changed_when: False
  tags: debug

- name: LINUX-ONLY debug output of the resolution
  debug:
    msg: "{{ lookup_output }}"
  tags: debug
