- name: LINUX-ONLY debugging to resolve a domain if possible
  command: nslookup "{{ lookup_test }}"
  register: lookup_output
  changed_when: False
  tags: debug

- name: LINUX-ONLY debug output of the resolution
  debug:
    msg: "{{ lookup_output }}"
  tags: debug

