---
- name: set resolv.conf on EL7
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644

- name: set dns for EL 7 based servers with NMCLI
  nmcli:
    conn_name: "{{ ansible_default_ipv4.interface }}"
    type: ethernet	
    dns4: "{{ resolv_nameservers }}"	
    state: present	

- name: restart NetworkManager with command
  command: /usr/bin/nmcli connection up "{{ ansible_default_ipv4.interface }}"

