---
- name: confirm NetworkManager installed
  yum:
    state: latest
    name: NetworkManager-glib

- name: set resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644

- name: set dns for EL 7 based servers
  nmcli:
    conn_name: "{{ ansible_default_ipv4.interface }}"
    type: ethernet
    dns4: "{{ resolv_nameservers }}"
    state: present
