---
- name: EL7-ONLY set dns with NMCLI module
  nmcli:
    conn_name: "{{ ansible_default_ipv4.interface }}"
    type: ethernet	
    dns4: "{{ resolv_nameservers }}"	
    state: present	
  tags: makeitso

- name: EL7-ONLY activate changes with nmcli
  command: /usr/bin/nmcli connection up "{{ ansible_default_ipv4.interface }}"
  tags: makeitso

- name: EL7-ONLY debugging to check interface status
  command: /usr/bin/nmcli dev show "{{ ansible_default_ipv4.interface }}"
  register: devshow_output
  tags: debug

- name: EL7-ONLY debug output of the file
  debug:
    msg: "{{ devshow_output }}"
  tags: debug

- name: EL7-ONLY debugging to check /etc/resolv.conf
  command: "cat /etc/resolv.conf"
  register: etcresolv_output
  tags: debug

- name: EL7-ONLY debug output of the file
  debug:
    msg: "{{ etcresolv_output }}"
  tags: debug

