---
- name: set dns for EL 7 based servers
  nmcli:
    conn_name: "{{ ansible_default_ipv4.interface }}"
    type: ethernet
    dns4: "{{ item }}"
    state: present
  with_items: "{{ dns_servers }}"
  notify: reload nmcli
