- name: Change nameserver settings in the interfaces file
  interfaces_file:
    dest: /etc/network/interfaces
    iface: "{{ ansible_default_ipv4.interface }}"
    option: dns-nameservers
    value: "{{ resolv_nameservers[0]|default ('') }} {{ resolv_nameservers[1]|default ('') }} {{ resolv_nameservers[2]|default ('') }}"	
    backup: yes
    state: present
  tags: makeitso

- name: debugging to check /etc/resolv.conf
  command: cat /etc/network/interfaces
  register: interface_output
  tags: debug

- name: debug output of the file
  debug:
    msg: "{{ interface_output }}"
  tags: debug

